---
title: "Check Results2"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(readxl)
library(DataExplorer)

library(gt)

dir <- getwd()   #Updates the path to the directory where the R Code is present
input_dir <- paste0(dir, "/Inputs/") 

output_dir <- paste0(dir , "/Outputs/")

ops_data_in <- read_excel("Tests/idb_data.xlsx", 
    sheet = "ops_data")

```


# Testing Method

The Disbursement Projection Model developed by Moody's Analytics is tested by using a generated test sample which is representative of the actual data. The objective here is to see how the model performs in the presence of new / unseen data.


```{r datainput sim, include=FALSE}

model_input_sim <- read_csv(file = paste0(input_dir, "isdb_test_prjs_sim.csv")) %>% 
  select( -...1) %>% 
  mutate( proj_type = str_replace(project_title,  '-.*' , ''))

model_output_sim <- readRDS( file = paste0(output_dir , "model_output_sim.rda")) %>% 
  janitor::clean_names() %>% 
  mutate(
    proj_type = str_replace(project_title,  '-.*' , '')
  )

profiles_sim <- readRDS(file = paste0(output_dir , "full_disb_profile_sim.rda")) %>% 
  janitor::clean_names()

```

```{r}
skimr::skim(model_input_sim)
```


```{r datainput comp, eval=FALSE, include=FALSE}


model_input_comp <- read_csv(file = paste0(input_dir, "isdb_test_prjs_comp.csv")) %>% 
  select( -...1) %>% 
  mutate( proj_type = str_replace(project_title,  '-.*' , ''))

model_output_comp <- readRDS( file = paste0(output_dir , "model_output_sim.comp")) %>% 
  janitor::clean_names() %>% 
  mutate(
    proj_type = str_replace(project_title,  '-.*' , '')
  )

profiles_comp <- readRDS(file = paste0(output_dir , "full_disb_profile_comp.rda")) %>% 
  janitor::clean_names()

```
