---
title: "Check Results"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(lubridate)
library(readxl)


```

```{r}

dir <- getwd()   #Updates the path to the directory where the R Code is present
input_dir <- paste0(dir, "/Inputs/") 

output_dir <- paste0(dir , "/Outputs/")

ops_data_check <- read_csv(file = paste0(input_dir, "isdb_test_prjs.csv"))

# profiles <- read_csv(file = paste0(output_dir , "IsDB Projects & LoF Disbursement Modelling Profiles idb_test 11-Jan-2022 15.56.12"))



profiles <- readRDS(file = paste0(output_dir , "full_disb_profile.rda")) %>% 
  janitor::clean_names()


model_output <- readRDS( file = paste0(output_dir , "model_output.rda")) %>% 
  janitor::clean_names()

write_csv(profiles , paste0(output_dir , "full_disb_profile.csv") )

```


```{r}

ops_data_check %>%  
  summarise( total_apr_amt = sum(approval_amount_usd)/1e6 , 
             amount_already_disb = sum(amount_disbursed_at_evaluation_date_usd)/1e6) %>% 
  mutate( total_disb_est = (total_apr_amt - amount_already_disb) )


profiles %>%  summarise( total_disb = sum( amount_disbursed_between_tenors ) /1e6 )

check1 <- ops_data_check %>% 
  left_join(
    profiles %>% 
      group_by(project_id) %>% 
      summarise( amt_disb = sum( amount_disbursed_between_tenors ) )
  )

check1 %>%  
  filter( approval_amount_usd != amt_disb) 





```

```{r}

#library(tidytext)

ops_data_check %>% glimpse()


model_input <-  test_data_in %>% 
  select( -...1) %>% 
  mutate( proj_type = str_replace(project_title,  '-.*' , ''))

theme_set(theme_minimal())

model_input %>% 
  group_by( proj_type ) %>% 
  count( sector , sort = T) %>% 
  mutate( sector = tidytext::reorder_within(sector,  n , proj_type)) %>% 
  ggplot(aes( sector , n)) +
  geom_col() +
  coord_flip() +
  tidytext::scale_x_reordered() +
  facet_wrap(~proj_type, scales = "free_y") 

```


```{r}

#eval_date <- dmy("01-01-2022")

bins <- seq(0, 14400 , 180)

theme_set(theme_minimal())

profiles <- profiles %>% 
    mutate( days_from_eval = time_length(date_of_disbursement - evaluation_day , "day"), 
    days_bin  = cut(days_from_eval , bins , include.lowest = TRUE)) 

profiles %>% 
  ggplot( aes(x = days_bin , amount_disbursed_between_tenors)) +
  geom_col(fill = "skyblue4")

```

# Plot data

```{r}
library(patchwork)


plot_hist <- function(data_src , var){
  
  mean_val = mean(var)
  
  #medean_val = median(var)
  
  var_name = str_remove( deparse(substitute(var)) , ".*\\$days_from_" )
  
  #geom_histogram(aes(y=..density.. , fill = ), fill="lightblue")+

  
  data_src %>% 
  ggplot(aes(var)) +
  #geom_histogram(aes(y=..density.. , fill = catch_up_shift ) )+
  geom_histogram(aes(y=..density.. ) , bins = 30 , alpha = .5)+
  #geom_density(alpha=.2, fill="#FF6666") +
  geom_density(alpha=.2) + 
  geom_vline(aes(xintercept= mean_val),
            color="black", linetype="dashed", size=.5 , alpha = .5) +
  # geom_vline(aes(xintercept= medean_val),
  #           color="blue", linetype="dashed", size=.5 , alpha = .5) +
  annotate("text" , x = mean_val , y  = 0 , label = paste0(sprintf("Avg. %.2f",mean_val)) , color = "red") +
  labs(title = var_name)
  
}
```



# Not Signed Projects

```{r}


data_in <- model_output %>% 
  filter(str_detect( project_title, "Not Signed" ) )

p1 <- plot_hist(data_in , data_in$days_from_approval_to_signature)
  
  
p2 <- plot_hist(data_in , data_in$days_from_signature_to_effectiveness)


p3 <- plot_hist(data_in , data_in$days_from_effectiveness_to_first_disbursement)
  
  
p4 <- plot_hist(data_in , data_in$days_from_first_to_final_disbursement)
  
 

(p1 | p2) / (p3 | p4) + plot_annotation(
  title = 'Model Output - Projects Not Signed',
  subtitle = 'Distribution of projected time-taken by milestones(months)',
  caption = paste0('Based on a sample input of ' , nrow(data_in) , ' Approved but not Signed projects')
)

```

# Not Effective Projects

```{r}


data_in <- model_output %>% 
  filter(str_detect( project_title, "Not Effective" ) )

#p1 <- plot_hist(data_in , data_in$days_from_approval_to_signature)
  
  
p2 <- plot_hist(data_in , data_in$days_from_signature_to_effectiveness)


p3 <- plot_hist(data_in , data_in$days_from_effectiveness_to_first_disbursement)
  
  
p4 <- plot_hist(data_in , data_in$days_from_first_to_final_disbursement)
  
 

(p2 | p3) / (p4) + plot_annotation(
  title = 'Model Output - Projects Not Effective',
  subtitle = 'Distribution of projected time-taken by milestones(months)',
  caption = paste0('Based on a sample input of ' , nrow(data_in) , ' Signed but not Effective projects')
)

```
