---
title: "Generate Project Test Data"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(lubridate)
library(readxl)


```


```{r envparam}

dir <- getwd()   #Updates the path to the directory where the R Code is present
input_dir <- paste0(dir, "/Inputs/") 

ops_data_in <- read_excel("Tests/idb_data.xlsx", 
    sheet = "ops_data")



```


```{r globalparam}
start_date <- dmy("01/01/2020")

end_date <- dmy("01/01/2023")

sample_size <- 100
```



```{r}

profiles <- ops_data_in %>% 
  group_by(profile) %>% 
  summarise( n = n() ) %>% 
  mutate( freq = n/sum(n))

countries <- ops_data_in %>% 
  distinct(country , country_class) %>% 
  mutate(
    income_classification = str_to_sentence(country_class)
  ) %>% 
  mutate(
    income_classification = str_replace(income_classification , "Low middle income" , "Lower middle income") ) %>% 
  select( -country_class) %>% 
  filter(country != "Not Assigned")

sectors <-  ops_data_in %>% 
  group_by(sector) %>% 
  summarise( n = n() ) %>% 
  mutate( freq = n/sum(n)) %>% 
  mutate( sector = str_to_title(sector) ) %>% 
  mutate( sector = str_replace(sector , "And" , "and") )
  


```




```{r}

eval_date <- dmy("01-01-2021")

set.seed(678)

ops_data <- ops_data_in %>% 
  transmute(
    project_id = operation_id,
    project_title,
    country, # = sample( t , size = 1),
    #sector = str_to_title(sector),
    approval_amount_usd = approval_amt_usd,
    profile, 
    #rating  = rating_2020,
    #registering_property = 0,                             
    #government_effectiveness = 0,                        
    sub_mode_of_finance,                             
    #income_classification = country_class,                            
    evaluation_date = eval_date,                                  
    amount_disbursed_at_evaluation_date_usd = NA,         
    date_of_approval,                                
    date_of_signature = NA,                                
    date_of_effectiveness = NA,                            
    date_of_first_disbursement = NA,                       
    days_from_approval_to_signature_cap = "",              
    days_from_signature_to_effectiveness_cap = "",         
    days_from_effectiveness_to_first_disbursement_cap = "",
    date_of_signature_override = "",                       
    date_of_effectiveness_override = "",                 
    date_of_first_disbursement_override = "",              
    date_of_final_disbursement_override= "",
    catchup_override = NA
  ) %>% filter( approval_amount_usd != 0 , #!is.na(income_classification),
                country != "Not Assigned", 
                !(sub_mode_of_finance %in% c("Loan LDMC", "Grant"))) 

# %>% 
#   mutate(
#     sector = str_replace(sector , "And" , "and")
#     # ,
#     # income_classification = str_to_sentence(income_classification)
#   ) 
  #%>% 
  # mutate(
  #   income_classification = str_replace(income_classification , "Low middle income" , "Lower middle income")
  # )

# %>% 
#   slice_sample(n=100)

rows <-  nrow(ops_data)

s_countries <- sample( countries$country , size = rows , replace = T)

#s_sectors <-  sample( sectors$sector , size = rows , replace = T)


#t <- profiles[c(1,3),]$profile

s_profile <- sample(profiles$profile, size = rows, replace = T  , prob = profiles$freq )


ops_data_out <-  ops_data %>% 
  mutate(
    country = s_countries,
    #sector = s_sectors,
    profile = s_profile
  )


#ops_data_out %>% select( project_title , country , sector , profile )


#ops_data %>% select( project_title , country , sector , profile )

```



# Load indicator data


## Governance
```{r}

hd_file <- paste0( input_dir , "Historical Data  Governance Indicators and Rating_157428296.xlsx" )

gov_effect <- read_excel( hd_file, 
    sheet = "GovernmentEffectiveness", skip = 7) %>% 
  rename( country_territory = ...1 ,
          country = ...2 ) %>% 
  slice(-1) %>% 
  select(-country_territory) %>% 
  mutate( across(2:48 , ~as.double(.x))) %>% 
  janitor::clean_names() 


gov_effect <- gov_effect %>% 
   pivot_longer(
    cols = starts_with("x"),
    names_to = "year",
    values_to = "government_effectiveness"
  ) %>% 
  mutate( year = as.integer( str_remove(year , "x") ) )

glimpse(gov_effect)

```


## Registering Property


```{r}

reg_property <- read_excel(hd_file, 
    sheet = "Registering Property", skip = 3) %>% 
  rename( country = ...1) %>% 
  mutate( "2021" = `2020`) %>% 
  pivot_longer(
    cols = 2:48,
    names_to = "year",
    values_to = "registering_property"
  ) %>% 
  mutate( year = as.integer(year))


reg_property %>%  glimpse()

```

## Ratings

```{r}

ratings <- read_excel(hd_file, 
    sheet = "Rating", skip = 5) %>% 
  rename( country = "Quarter/Country") %>% 
  pivot_longer(
    cols = 2:188,
    names_to = "year_quarter",
    values_to = "rating"
  )
  

ratings %>%  glimpse()

```



```{r}
test_data <- ops_data_out
```




# Not Signed Projects

```{r}
set.seed(567)

base_date <- sample(seq( start_date , end_date , by = "day") , size = sample_size , replace = T)

apr_offset_m <- months(sample( seq(1,12) , size = sample_size , replace = T))

apr_offset_d <- sample( seq(1:30) , size = sample_size , replace = T)

eval_offset_m <- months(sample( seq(1,12) , size = sample_size , replace = T))

eval_offset_d <- sample( seq(1:30) , size = sample_size , replace = T)

s_sectors <-  sample( sectors$sector , size = sample_size , replace = T , prob = sectors$freq)

set.seed(234)

test_data_sig <- 
  test_data %>% 
  slice_sample(n = sample_size) %>% 
  mutate(
    project_id_org = project_id,
    project_title_org = project_title,
    project_id = paste0( "NS", formatC(row_number(), width=3, flag="0") ),
    project_title = paste0( "Not Signed-", formatC(row_number(), width=3, flag="0") ),
    date_of_approval = base_date %m+% apr_offset_m + apr_offset_d,
    evaluation_date = date_of_approval  %m+% eval_offset_m + eval_offset_d,
    sector = s_sectors
  )


test_data_in <- test_data_sig

```

# Signed Not Effective Projects

```{r}

set.seed(789)

base_date <- sample(seq( start_date , end_date , by = "day") , size = sample_size , replace = T)

apr_offset_m <- months(sample( seq(1,12) , size = sample_size , replace = T))

apr_offset_d <- sample( seq(1:30) , size = sample_size , replace = T)

eval_offset_m <- months(sample( seq(1,12) , size = sample_size , replace = T))

eval_offset_d <- sample( seq(1:30) , size = sample_size , replace = T)

sig_offset_m <- months(sample( seq(1,12) , size = sample_size , replace = T))

sig_offset_d <- sample( seq(1:30) , size = sample_size , replace = T)


s_sectors <-  sample( sectors$sector , size = sample_size , replace = T , prob = sectors$freq)


test_data_eff <- 
  test_data %>% 
  slice_sample(n = sample_size) %>% 
  mutate(
    project_id_org = project_id,
    project_title_org = project_title,
    project_id = paste0( "NE", formatC(row_number(), width=3, flag="0") ),
    project_title = paste0( "Not Effective-", formatC(row_number(), width=3, flag="0") ),
    evaluation_date = eval_date,
    date_of_approval = base_date %m+% apr_offset_m + apr_offset_d,
    date_of_signature = date_of_approval %m+% sig_offset_m + sig_offset_d,
    evaluation_date = date_of_signature  %m+% eval_offset_m + eval_offset_d,
    sector = s_sectors
  )

test_data_in <- 
  test_data_in %>% 
  bind_rows(test_data_eff)


```


# Effective but not disbursing projects
```{r}
set.seed(1234)

base_date <- sample(seq( start_date , end_date , by = "day") , size = sample_size , replace = T)

apr_offset_m <- months(sample( seq(1,12) , size = sample_size , replace = T))

apr_offset_d <- sample( seq(1:30) , size = sample_size , replace = T)

eval_offset_m <- months(sample( seq(1,12) , size = sample_size , replace = T))

eval_offset_d <- sample( seq(1:30) , size = sample_size , replace = T)

sig_offset_m <- months(sample( seq(1,12) , size = sample_size , replace = T))

sig_offset_d <- sample( seq(1:30) , size = sample_size , replace = T)

eff_offset_m <- months(sample( seq(1,12) , size = sample_size, replace = T))

eff_offset_d <- sample( seq(1:30) , size = sample_size, replace = T)

s_sectors <-  sample( sectors$sector , size = sample_size , replace = T , prob = sectors$freq)

test_data_fstd <- 
  test_data %>% 
  slice_sample(n = sample_size) %>% 
  mutate(
    project_id_org = project_id,
    project_title_org = project_title,
    project_id = paste0( "ND", formatC(row_number(), width=3, flag="0") ),
    project_title = paste0( "Not Disbursing-", formatC(row_number(), width=3, flag="0") ),
    evaluation_date = eval_date,
    date_of_approval = base_date %m+% apr_offset_m + apr_offset_d,
    date_of_signature = date_of_approval %m+% sig_offset_m + sig_offset_d,
    date_of_effectiveness = date_of_signature %m+% eff_offset_m + eff_offset_d,
    evaluation_date = date_of_effectiveness  %m+% eval_offset_m + eval_offset_d,
    sector = s_sectors
  )

test_data_in <- 
  test_data_in %>% 
  bind_rows(test_data_fstd)


```

# Disbursing Projects

```{r}

set.seed(5467)

base_date <- sample(seq( start_date , end_date , by = "day") , size = sample_size , replace = T)

apr_offset_m <- months(sample( seq(1,12) , size = sample_size , replace = T))

apr_offset_d <- sample( seq(1:30) , size = sample_size , replace = T)

eval_offset_m <- months(sample( seq(1,12) , size = sample_size , replace = T))

eval_offset_d <- sample( seq(1:30) , size = sample_size , replace = T)

sig_offset_m <- months(sample( seq(1,12) , size = sample_size , replace = T))

sig_offset_d <- sample( seq(1:30) , size = sample_size , replace = T)

eff_offset_m <- months(sample( seq(1,12) , size = sample_size, replace = T))

eff_offset_d <- sample( seq(1:30) , size = sample_size, replace = T)

fstd_offset_m <- months(sample( seq(1,12) , size = sample_size, replace = T))

fstd_offset_d <- sample( seq(1:30) , size = sample_size, replace = T)

pct_disb <- sample( seq(0,1,0.0125) , size = sample_size, replace = T)

s_sectors <-  sample( sectors$sector , size = sample_size , replace = T , prob = sectors$freq)

test_data_lstd <- 
  test_data %>% 
  slice_sample(n = sample_size) %>% 
  mutate(
    project_id_org = project_id,
    project_title_org = project_title,
    project_id = paste0( "CD", formatC(row_number(), width=3, flag="0") ),
    project_title = paste0( "Disbursing-", formatC(row_number(), width=3, flag="0") ),
    date_of_approval = base_date %m+% apr_offset_m + apr_offset_d,
    date_of_signature = date_of_approval %m+% sig_offset_m + sig_offset_d,
    date_of_effectiveness = date_of_signature %m+% eff_offset_m + eff_offset_d,
    date_of_first_disbursement = date_of_effectiveness %m+% fstd_offset_m + fstd_offset_d,
    evaluation_date = date_of_first_disbursement  %m+% eval_offset_m + eval_offset_d,
    amount_disbursed_at_evaluation_date_usd = approval_amount_usd * pct_disb,
    sector = s_sectors
  )

test_data_in <- 
  test_data_in %>% 
  bind_rows(test_data_lstd) %>% 
  mutate(amount_disbursed_at_evaluation_date_usd = replace_na(amount_disbursed_at_evaluation_date_usd , 0))


```

# Merge additional data with the main data

```{r}

test_data_in <- test_data_in %>% 
  left_join(countries , by = c ("country" = "country")) %>% 
  relocate( income_classification , .after = sub_mode_of_finance ) %>% 
  mutate( year = case_when( 
    year(date_of_approval) > 2021 ~ as.integer(2021),
    TRUE ~ as.integer(year(date_of_approval)) ) ) %>% 
  left_join( gov_effect , by = c("country" = "country", "year" = "year") ) %>% 
  left_join( reg_property , by = c("country" = "country", "year" = "year") ) %>% 
  relocate(government_effectiveness , .before = sub_mode_of_finance) %>% 
  relocate(registering_property , .before = sub_mode_of_finance ) %>% 
  mutate( year_quarter = case_when(
    year == 2021 & quarter(date_of_approval) == 4 ~ paste0( year , "Q3" ),
    year == 2021 ~ paste0( 2021 , "Q3" ),
    TRUE ~ paste0( year , "Q" , quarter(date_of_approval)   ) ) ) %>% 
  left_join( ratings  , by = c("country" = "country", "year_quarter" = "year_quarter")  ) %>% 
  relocate( rating , .after = profile ) %>%
  select( -year , -year_quarter)


test_data_in %>% glimpse()


```



```{r eval=FALSE, include=FALSE}
test_data_in %>% select(project_id, project_title , date_of_approval , date_of_signature, date_of_effectiveness, date_of_first_disbursement) %>% view()



test_data_in %>% glimpse()


```




```{r}

write.csv(test_data_in %>% 
            filter( year(date_of_approval) > 2016 ),
            file = paste0(input_dir, "isdb_test_prjs.csv"))
#  %>% slice_sample(n=100), 
```

```{r eval=FALSE, include=FALSE}
test_data_sig %>% count(sector , sort = T)

test_data_eff %>% count(sector , sort = T)

test_data_fstd %>% count(sector , sort = T)

test_data_lstd %>% count(sector , sort = T)


model_input <-  test_data_in %>% 
  #select( -...1) %>% 
  mutate( proj_type = str_replace(project_title,  '-.*' , ''))

theme_set(theme_minimal())

model_input %>% 
  group_by(  proj_type,  sector ) %>% 
  summarise( n = n() ) %>% 
  mutate( sector = tidytext::reorder_within(sector,  n , proj_type)) %>% 
  ggplot(aes( sector , n)) +
  geom_col() +
  coord_flip() +
  tidytext::scale_x_reordered() +
  facet_wrap(~proj_type, scales = "free_y") 


```

